#!/bin/bash

OUT_NAME="TF Newcomer Guide"

source_names=(
    guide.md
    kitchen.md
    dehydrator.md
    "food processing.md"
    hammock.md
    )

# add directory to file names
sources=()
for n in "${source_names[@]}"
do
    sources+=( "text/$n" )
done

# EPUB
pandoc text/meta.md "${sources[@]}" --epub-cover-image=res/cover.svg -o "$OUT_NAME.epub"

# # ODT
# pandoc res/cover.svg "${sources[@]}" -o "$OUT_NAME.odt"
# 
# # ODT to PDF
# libreoffice  --convert-to pdf "../${OUT_NAME}.odt"

# EPUB to PDF
ebook-convert TF\ Newcomer\ Guide.epub TF\ Newcomer\ Guide.pdf