name: Docker Image CI
on:
  workflow_dispatch:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      uses: docker/build-push-action@v3
      run: docker build . --file ~/Dockerfile --tag my-image-name:$(date +%s)
      with:
        context: .
