name: Docker Image CI
- name: Build and push
  uses: docker/build-push-action@v3
  with:
    context: .
on:
  workflow_dispatch:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file ~/Dockerfile --tag my-image-name:$(date +%s)
